engines:
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: 'C'
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 300
  fixme:
    enabled: true
ratings:
   paths:
   - "**.py"
exclude_paths:
- "src/gfx/**/*"
- "**.ui"
- "**.qrc"
- "**.yml"
- "**.bat"
- "**.md"
- "setup.cfg"
- "run"
- "build"
- "LICENSE"
- ".codeclimate.yml"
