language: objective-c

before_install:
- sudo chown -R `whoami` /Library/Python

install:
- python --version
- pip --version
- wget https://download.qt.io/archive/qt/4.8/4.8.6/qt-opensource-mac-4.8.6-1.dmg
- hdiutil mount qt-opensource-mac-4.8.6-1.dmg
- sudo installer -verbose -pkg /Volumes/Qt\ 4.8.6/Qt.mpkg -target /
- pip install -U PySide
- python -c "import PySide"
- pip install -U PyOpenGL
- pip install -U PyOpenGL_accelerate
- pip install -U py2app

script:
- cp LICENSE blender_addon
- cd blender_addon
- zip zoxel-$TRAVIS_TAG-blender-addon.zip *
- cd ..
- ./build
- cd src
- python setup.py py2app
- cd dist
- tar czf zoxel-$TRAVIS_TAG-osx.tar.gz zoxel.app

deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - src/dist/zoxel-$TRAVIS_TAG-osx.tar.gz
    - blender_addon/zoxel-$TRAVIS_TAG-blender-addon.zip
  on:
    repo: chrmoritz/zoxel
    tags: true
