language: objective-c

branches:
  only:
    - /^v?\d+(\.\d+)*$/

before_install:
- sudo chown -R `whoami` /Library/Python

install:
- python --version
- pip --version
- wget http://pyside.markus-ullmann.de/pyside-1.2.1-qt4.8.5-py27apple-developer-signed.pkg
- sudo installer -verbose -pkg pyside-1.2.1-qt4.8.5-py27apple-developer-signed.pkg -target /
- wget https://download.qt.io/archive/qt/4.8/4.8.6/qt-opensource-mac-4.8.6-1.dmg
- hdiutil mount qt-opensource-mac-4.8.6-1.dmg
- sudo installer -verbose -pkg /Volumes/Qt\ 4.8.6/Qt.mpkg -target /
- python -c "import PySide"
- pip install PyOpenGL
- pip install PyOpenGL_accelerate
- pip install py2app

script:
- ./build
- cd src
- python setup.py py2app
- cd dist
- ls -la
- tar czf ../../zoxel-0.5-osx.tar.gz zoxel.app

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: yUf0zKDRpTvShF1nw7I+FlZQ522Hb0x8yg+aw53aVmqEVe8oZSHk0U1IwJ47uIVGARbC3V/Z4Ly93jDtZZIGQTFYd/bfcBIbX0mEzMlGtOblzaXXWmeB0Il7Zr945t1MnhAQbsK90v4NCaDFsoZkUIcc1pCt1uIAdw34xYt+980=
  file: zoxel-0.5-osx.tar.gz
  on:
    repo: chrmoritz/zoxel
    tags: true
    all_branches: true
