language: objective-c

before_install:
- brew update

install:
- brew install python
- brew install qt
- brew install pyside
- brew install pyside-tools
- pip install -U PyOpenGL
- pip install -U PyOpenGL_accelerate
- pip install -U py2app

script:
- cp LICENSE blender_addon
- cd blender_addon
- zip zoxel-$TRAVIS_TAG-blender-addon.zip *
- cd ..
- ./build
- cd src
- python setup.py py2app
- cd dist
- tar czf zoxel-$TRAVIS_TAG-osx.tar.gz zoxel.app
- cd ../../

cache:
  directories:
    - /usr/local/lib/python2.7/site-packages

deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - src/dist/zoxel-$TRAVIS_TAG-osx.tar.gz
    - blender_addon/zoxel-$TRAVIS_TAG-blender-addon.zip
  on:
    repo: chrmoritz/zoxel
    tags: true
