os: Visual Studio 2015
version: '{branch}-b{build}'

init:
  - ps: "ls -Name \"C:/\""
  - SET PATH=C:\Python27;C:\Python27\Scripts;%PATH%

install:
  - ps: Start-FileDownload 'https://bootstrap.pypa.io/get-pip.py'
  - python get-pip.py
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - pip --version
  - pip install -U PySide
  - python -c "import PySide"
  - pip install -U cx_freeze
  - pip install -U PyOpenGL
  - pip install -U PyOpenGL_accelerate

build_script:
  - cd /D %APPVEYOR_BUILD_FOLDER%
  - python build.py --verbose --with-exe
  - cd dist
  - IF NOT DEFINED APPVEYOR_REPO_TAG_NAME set APPVEYOR_REPO_TAG_NAME=%APPVEYOR_REPO_COMMIT:~0,7%
  - ps: "& 7z a -r zoxel-$env:APPVEYOR_REPO_TAG_NAME-win32.zip ."

test: off

artifacts:
  - path: dist/zoxel-$(APPVEYOR_REPO_TAG_NAME)-win32.zip

deploy:
  provider: GitHub
  auth_token:
    secure: DUZQbCQFI4HKfOcnF+S9Krti2Kz1agHaSLFUJv8mK8Ov/DjeOhR9YyEkqLGY/I9J
  artifact: dist/zoxel-$(APPVEYOR_REPO_TAG_NAME)-win32.zip
  prerelease: true
  on:
    appveyor_repo_tag: true
