os: Visual Studio 2015
version: '{branch}-b{build}'

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_ARCH: "win32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_ARCH: "win64"

init:
  - ps: "ls -Name \"C:/\""
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - IF NOT DEFINED APPVEYOR_REPO_TAG_NAME set APPVEYOR_REPO_TAG_NAME=%APPVEYOR_REPO_COMMIT:~0,7%

install:
  - ps: Start-FileDownload 'https://bootstrap.pypa.io/get-pip.py'
  - python get-pip.py
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - pip --version
  - pip install -U PySide
  - python -c "import PySide"
  - pip install -U cx_freeze
  - pip install -U PyOpenGL
  - pip install -U PyOpenGL_accelerate

build_script:
  - python build.py --verbose --with-exe --with-msi

test: off

artifacts:
  - path: zoxel-$(APPVEYOR_REPO_TAG_NAME)-$(PYTHON_ARCH).zip
  - path: src\dist\Zoxel-*.msi

deploy:
  provider: GitHub
  auth_token:
    secure: DUZQbCQFI4HKfOcnF+S9Krti2Kz1agHaSLFUJv8mK8Ov/DjeOhR9YyEkqLGY/I9J
  artifact: zoxel-$(APPVEYOR_REPO_TAG_NAME)-$(PYTHON_ARCH).zip,src\dist\Zoxel-$(APPVEYOR_REPO_TAG_NAME)-$(PYTHON_ARCH).msi
  prerelease: true
  on:
    appveyor_repo_tag: true
